name: CI

on:
  push:
    branches: [ main, master, development ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: golang:1.25
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # полный clone для VCS stamping

      - name: Download dependencies
        run: go mod download

      - name: Run tests with race detector
        run: go test -v -race -buildvcs=false ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: golang:1.25
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest

      - name: Build custom golangci-lint
        run: |
          cd plugin
          golangci-lint custom

      - name: Run linter
        run: ./custom-gcl run ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    container: golang:1.25
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build binary
        run: CGO_ENABLED=0 GOOS=linux go build -buildvcs=false -o loglinter ./cmd/loglinter/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: loglinter
          path: loglinter
